### PR TITLE
Clarify 'waydroid init' options ('-c', '-v') on Fedora

### PR DESCRIPTION
**Pull request by plata**
see https://github.com/waydroid/waydroid/issues/891#issuecomment-1537444388

### CODE REVIEW

**Comment by Quackdoc** [comment]
Im not sure this should be an error within the script, or if it is, maybe a runtime error that checks distro would be better

**Comment by plata** [comment]
@aleasto can you clarify?

**Comment by aleasto** [comment]
This does not make sense here because Fedora disables it with a downstream patch.
If anything this should be also a downstream patch in Fedora.

Some generic runtime check could also work.

**Comment by plata** [comment]
Are you maintaining that patch? If so, could you remove "; default is Official OTA server" with the patch?

For my curiosity: What's the reason to exclude the default on Fedora?

**Pull request closed without merging**
