### PR TITLE
Add Makefile buildsystem

### PR DESCRIPTION
**Pull request by JamiKettunen**
This aims to solve the packaging mess currently in the wild with each distribution doing essentially duplicate work manually copying the needed files/dirs to the correct locations; also avoids new changes being missed in some distro packaging when everyone just `make install`s the same things.

### CODE REVIEW

**Comment by aleasto** [comment]
Couple of requests from fedora:
* USE_SYSTEMD is not configurable from outside
* Add something to switch waydroid-net to nftables, like `sed -i '/LXC_USE_NFT=/s/false/true/' $(WAYDROID_DIR)/data/scripts/waydroid-net.sh`

**Comment by JamiKettunen** [comment]
> USE_SYSTEMD is not configurable from outside

@aleasto how precicely? `make install USE_SYSTEMD=0` works for me, or is it something else missing? like being able to set `USE_SYSTEMD=0` in env and just `make_install`?

**Comment by aleasto** [comment]
Yea. same for `PREFIX` maybe.
Should be enough to switch to `?=` iirc

**Comment by JamiKettunen** [comment]
Yep `?=` will do it, what about all the others (`*_DIR` vars)? I mean it shouldn't really hurt to make them changeable via env should it?

**Comment by aleasto** [comment]
Ehh i don't know. There's some hardcoded paths in waydroid. Changing PREFIX probably already breaks stuff

**Comment by JamiKettunen** [comment]
Ah yes, there's some hardcoded stuff currently:
- `systemd/waydroid-container.service` hardcodes `/usr/bin/waydroid`
- `data/{waydroid.market,Waydroid}.desktop` both harcode icon as `/usr/lib/waydroid/data/AppIcon.png` (different icon sizes when along with an svg? :p)
- `tools/config/__init__.py` harcodes `/usr/share/waydroid-extra`
(found with a simple grep for `/usr`)

Should anything be done about this? What about disallowing change of `PREFIX` for now?

**Comment by aleasto** [comment]
Eh, keep it as is.

**Comment by aleasto** [comment]
fyi i've added a new file, `./polkit/*`

**Comment by JamiKettunen** [comment]
Tested the `debian/*` changes enough to see it produces similar enough contents (`dpkg -c waydroid_*_all.deb `) to the old packaging, think this is ready for review and proper testing now.

**Review by aleasto — APPROVED** [review]

**Comment by aleasto** [comment]
One thing I want to make sure is that waydroid-container is still automatically enabled and started on install

**Pull request merged**
