### PR TITLE
Added Code Of Conduct

### PR DESCRIPTION
**Pull request by SaptarshiSarkar12**
Added **Code Of Conduct** for this open source project to make it _better_ in terms of **community standards**.
**Code Of Conduct** in a project makes it more community driven which is what open-source aims at. So, I hope adding this would add a value to the project by increasing its community standards.

### CODE REVIEW

**Comment by SaptarshiSarkar12** [comment]
@aleasto Please review this pull request.

**Comment by SaptarshiSarkar12** [comment]
@aleasto Please review this.

**Comment by erfanoabdi** [comment]
i think its fine

**Comment by SaptarshiSarkar12** [comment]
Thank you for your review @erfanoabdi :+1: !

**Comment by SaptarshiSarkar12** [comment]
@aleasto Please look into it and check if it is merge-able.

**Comment by SaptarshiSarkar12** [comment]
Thank you @aleasto for merging this PR 🎉 !

**Pull request merged**
