### PR TITLE
container: workaround weird log permission bug

### PR DESCRIPTION
**Pull request by sigmaSd**

### CODE REVIEW

**Comment by erfanoabdi** [comment]
how about `os.chmod(args.log, 0o666)`

**Comment by sigmaSd** [comment]
done

**Comment by sigmaSd** [comment]
I'm not 100% sure but I think the permission still changes by some othe paths in the code.

I think the safest thing is to put the chmodding here https://github.com/waydroid/waydroid/blob/bullseye/tools/helpers/lxc.py#L247

**Comment by erfanoabdi** [comment]
merged

**Pull request closed without merging**
