### PR TITLE
tools: improve permission handling

### PR DESCRIPTION
**Pull request by sigmaSd**

### CODE REVIEW

**Comment by erfanoabdi** [comment]
maybe someone has wayland on root, in that case seesion must run as root

**Comment by erfanoabdi** [comment]
also app actions doesn't need root

**Comment by sigmaSd** [comment]
> maybe someone has wayland on root, in that case seesion must run as root
Yeah, too bad this would have caught a lot of misuse tough

> also app actions doesn't need root
In my testing app install/remove fails without root (but launch/list are ok)

**Comment by sigmaSd** [comment]
@erfanoabdi I figured why launch/remove needs sudo

Its because of ~/.local/share/waydroid/data

Initially its created with 777, but after Android writes to it, it becomes 771, which make it un-writable.

Is this the intended behavior?

**Comment by erfanoabdi** [comment]
oof permissions, no that's not intended and 771 is weird
i think umask is getting changed at some point, no idea

**Comment by sigmaSd** [comment]
@erfanoabdi What if I change the runtime error to a warning? I think its true that people can have wayland as root but I don't think its the common case (and its a warning anyway). And I'll remove the subactions path for now, those I guess need an actual fix for the  data permission

**Pull request closed without merging**
