### PR TITLE
Update issue temple

### PR DESCRIPTION
**Pull request by dabao1955**
Compared with markdown, yaml may be more focused on the required information, and will not easily destroy the content in the template.

### CODE REVIEW

**Comment by dabao1955** [comment]
> looks fine to me
> 

So I have a question: Do you know when my PR will be processed?

**Comment by Quackdoc** [comment]
sadly it's very much when someone gets the time too, devs are quite busy lately so it may take some time

**Comment by dabao1955** [comment]
> sadly it's very much when someone gets the time too, devs are quite busy lately so it may take some time

Well，Thank you for your reply.

**Comment by aleasto** [comment]
How may I see the result before merging?

**Comment by dabao1955** [comment]
> How may I see the result before merging?

How about screenshots?

**Comment by aleasto** [comment]
> > How may I see the result before merging?
> 
> How about screenshots?

Sure

**Comment by dabao1955** [comment]
> > > How may I see the result before merging?
> > 
> > How about screenshots?
> 
> Sure



Looks like this.

**Comment by aleasto** [comment]
Can you look into making the bug report template a form as well?
With proper places to upload logs and such...

**Comment by dabao1955** [comment]
> Can you look into making the bug report template a form as well?
> With proper places to upload logs and such...

Sure.

**Comment by dabao1955** [comment]
Screenshot_2023-09-01-18-58-36-08_df198e732186825c8df26e3c5a10d7cd
Finished.

**Pull request merged**
