### PR TITLE
tools: Fix device names with spaces in initializer

### PR DESCRIPTION
**Pull request by fredldotme**
Don't try to fetch from an URL with a space inside.

### CODE REVIEW

**Comment by erfanoabdi** [comment]
Wondering whats ro.product.device on jingpad that has space!?
isn't it illegal to put space in device codename?

**Comment by fredldotme** [comment]
That's with Jing's default vendor image, don't know what they screwed up here.
Might check and overlay things in the meantime, but you are right, it actually sounds like illegal behavior.

**Comment by erfanoabdi** [comment]
i don’t mind merging this change, was just curious lol

**Comment by Fuseteam** [comment]
what currently blocking this PR?

**Comment by erfanoabdi** [comment]
sorry, i forgot

**Pull request merged**
