### PR TITLE
fix appmenu folder groups for waydroid

### PR DESCRIPTION
**Pull request by mt190502**
image

### CODE REVIEW

**Comment by YukisawaNya** [comment]
> not everyone will want this

Almost every Linux developer put their desktop entry under certian group. Only waydroid don't. Why someone in waydroid dev team dislike it and reject it?

**Comment by Quackdoc** [comment]
not on the waydroid team, just an (lesser so now) active community member.

I don't like the idea of forcibly creating a new menu folder. I wouldn't like it in other apps, and I wouldn't like it in waydroid.

adding a command to create the menu should work fine, since it would be a one command/button to create the file. and then it wouldn't need to run again.

**Comment by aleasto** [comment]
There's no reason to have these created at runtime, right?
They could go in the /usr filesystem at packaging time

**Comment by Quackdoc** [comment]
how about a dedicated command for creating the folder? ill make a seperate issue for this but one thing I was thinking of would be a waydroid util function for running various commands/scriptlets, to help converge/fetch popular 3rd scripts. an example of how this would work would be

`waydroid util add-appmenu-folder`

**Pull request closed without merging**
