### PR TITLE
tools: Remove umask(0)

### LINKED ISSUE #43: Excessive permissions in `/var/lib/waydroid`
Besides the `.cfg` file having write permission to all, the write permission to directories is completely excessive
```shell
drwxrwxrwx. 1 root root    0 Sep 12 18:07 cache_http
drwxrwxrwx. 1 root root    0 Sep 12 18:07 host-permissions
drwxrwxrwx. 1 root root   40 Sep 12 18:07 images
drwxrwxrwx. 1 root root    0 Sep 12 18:07 rootfs
-rw-rw-rw-. 1 root root 1848 Sep  6 21:38 tools.log
-rw-rw-rw-. 1 root root  419 Sep 12 18:07 waydroid.cfg
-rw-rw-rw-. 1 root root 2240 Sep 12 18:38 waydroid.log
```
It might be due to botched installation, but if these are indeed set so by  the installer, consider changing them. If it is an error with the installer, there should be failsafe to not allow those permissions.

### PR DESCRIPTION
**Pull request by maringuu**
Closes #43

### CODE REVIEW

**Review by electrikjesus — APPROVED** [review]
This is fine. Approved on my end

**Comment by erfanoabdi** [comment]
it breaks some stuffs i don't remember right now, needs more testing

**Comment by ChrysoliteAzalea** [comment]
I checked today -- the waydroid session doesn't start if write access to ```waydroid.log``` is denied, but write access to other files and directories can be made for root only.

**Comment by JamiKettunen** [comment]
This was already implemented with https://github.com/waydroid/waydroid/commit/da4772c4e54467920d642e2a792c5d16d3b7bf33 as a part of https://github.com/waydroid/waydroid/pull/662, should be closed.

**Pull request closed without merging**
