### PR TITLE
Limit ADBD permissions through more restrictive AppArmor profile in order to prevent abuse and privilege escalation by unprivileged host users

### PR DESCRIPTION
**Pull request by ChrysoliteAzalea**
Hello everyone! Last year [I have submitted AppArmor profiles for the Android container](https://github.com/waydroid/waydroid/pull/506). However, these profiles were written in order to prevent abuse by apps. ADBD was not considered dangerous as it is a tool for external intervention. However, [recently I have discovered](https://github.com/waydroid/waydroid/issues/979) that an unprivileged user on a host system can start Waydroid, then enable root debugging and use the ADB in order to get root (which is an actual root on the host since the container is privileged). It is still restricted by being in a container and additionally by AppArmor profiles and seccomp filtering, and it can only get capabilities that are [accessible in the container](https://github.com/waydroid/waydroid/pull/504). However, such restrictions do not seem enough for me, so I propose a more restrictive AppArmor profile for ADBD. In that profile, following restrictions have been added:

* ```/proc``` is now read-only, with write permissions for owner only
* Removing access to abstract Unix sockets (I do not know whether Android uses them)
* ```/var``` and ```/run``` are now read-only, since they seem to be bind-mounted from the host and can be used to manipulate host system
* Some directories I am not sure about are now read-only
* Capabilities are seriously limited in order to ensure nothing system-wide or unsafe for the host can happen in a debugging session
* Mounting and unmounting are disallowed because it can be used to manipulate privileged processes in the container by bind-mounting
* Tracing is restricted because in can be used to manipulate privileged processes
* Signalling is also restricted -- ADBD can only signal itself and apps

These things are confirmed to break:
* ```adb remount``` no longer works, however, it can be done through ```waydroid shell```
* ```adb root``` works, however, its abilities are seriously limited. In order to perform privileged things, users should use ```waydroid shell```, which is only accessible to desktop root

### CODE REVIEW

**Comment by Quackdoc** [comment]
does this conflict with #906? if not ill try and test these tommorow and verify I cant run into an issues

**Comment by ChrysoliteAzalea** [comment]
As far as I understand, it shouldn't -- both pull requests switch the **adbd** profile into **enforce** mode.

**Comment by aleasto** [comment]
I'm not sure. Perhaps the feature should be disabled entirely, as apparmor would cover only a subset of waydroid usage.

**Comment by Quackdoc** [comment]
the question is, is there any real world usecase for leaving it enabled?

I don't have strong feelings one way or the other, but I am personally of the opinion that running waydroid (or really any root container) without appropriate SELinux/Apparmor and other security configs stuff should be considered unsafe anyways. I think we should do the best to secure waydroid as much as possible. so if we can do that via Apparmor/SELinux configs without removing *useful* features im all for that. 

that being said if there is no usecase for leaving it enabled, I would prefer outright disabling it

**Comment by aleasto** [comment]
The feature here is being nerfed to dubious usefulness in any case, as per Azalia's own comments

**Comment by Quackdoc** [comment]
profiles are something a user could override if need be, but I genuinely can't think of any use, so I'm for removing it entirely

**Comment by ChrysoliteAzalea** [comment]
I think that we can allow running ADBD as ```shell``` user, but disallow the ```adb root``` since we have other ways to do privileged things (from ```waydroid shell``` to Magisk).

**Comment by ChrysoliteAzalea** [comment]
[I've propose a patch to the ADBD in order to unconditionally block the ```adb root``` command](https://github.com/waydroid/android_vendor_waydroid/pull/22).

**Comment by ChrysoliteAzalea** [comment]
Closing this pull request as [ADBD in Waydroid no longer allows restarting as root](https://github.com/waydroid/android_vendor_waydroid/pull/23).

**Pull request closed without merging**
