### PR TITLE
Show progress while downloading android image

### PR DESCRIPTION
**Pull request by sigmaSd**

### CODE REVIEW

**Comment by electrikjesus** [comment]
This is working in testing. +1

**Review by electrikjesus — COMMENTED** [review]
It mostly works. 

user@user-Surface-Pro-3:~/anbox-halium$ sudo ./waydroid.py init -f
[17:18:59] Missing system or vendor on preinstalled images dir, fallback to default
[17:19:01] Stopping container
[17:19:01] Download https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-17.1-20210925-VANILLA-waydroid_x86_64-system.zip/download
[17:25:34] Validating system image
[17:25:36] Extracting to /var/lib/waydroid/images
Exception in thread Thread-1:7882
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/anbox-halium/tools/helpers/http.py", line 36, in progress
    while totalSize != os.path.getsize(destinationPath):
  File "/usr/lib/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/waydroid/cache_http/lineage-17.1-20210925-VANILLA-waydroid_x86_64-system.zip_a223ff9be1ca48fedaa6e24b3a17026c33facf5d03304b98c9db502a9c8a7453'
[17:25:59] Download https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-17.1-20210925-MAINLINE-waydroid_x86_64-vendor.zip/download
[17:27:18] Validating vendor image
[17:27:18] Extracting to /var/lib/waydroid/images
Exception in thread Thread-2:9026
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/anbox-halium/tools/helpers/http.py", line 36, in progress
    while totalSize != os.path.getsize(destinationPath):
  File "/usr/lib/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/waydroid/cache_http/lineage-17.1-20210925-MAINLINE-waydroid_x86_64-vendor.zip_5158edc2afadfa31ff45cf04b6621caf5c661c06a0d037cb847301586debc4e1'
[17:27:21] Starting container

**Comment by sigmaSd** [comment]
@electrikjesus I pushed a new commit, would you retest it?

**Comment by sigmaSd** [comment]
I guess this commit will make printing downloading.. overlap with Validating.. and  Extracting..

**Comment by sigmaSd** [comment]
I pushed a new commit with a simpler method, I think it should work now.

**Comment by electrikjesus** [comment]
Now it's working as expected. +1

**Pull request merged**
