### PR TITLE
add bash completion

### PR DESCRIPTION
**Pull request by Fuseteam**

### CODE REVIEW

**Comment by erfanoabdi** [comment]
oh sorry for closing this accidentally happened after removing master branch
this need to get updated from python autocomplete tho

**Comment by Fuseteam** [comment]
huh hmmm what do you mean update from python complete?

**Comment by erfanoabdi** [comment]
i meant something like `eval "$(register-python-argcomplete waydroid)"`

**Comment by Fuseteam** [comment]
.....huh? hmmmmm

**Pull request closed without merging**
