### PR TITLE
Add iptables as Debian dependency

### PR DESCRIPTION
**Pull request by DavidHenryThoreau**

### CODE REVIEW

**Comment by TriMoon** [comment]
https://github.com/waydroid/waydroid/issues/903#issuecomment-1658322659

> Wow, iptables has been deprecated from official Debian releases for 4 years, and Waydroid is still experiencing this issue until now.

**Comment by Quackdoc** [comment]
> So instead of this PR, a better solution would be to eliminate the `iptables` usage in the first place...
> Unless it's acceptable to have a follow-up PR that undoes this PR also while trying to get rid of `iptables` in the future..

iptables isn't a requirement, it's a recommendation and the sane default config. distros don't want to ship iptables can ship nftables instead via a simple patch in waydroid-net.sh. nftables has caused issues in the past. 

as for this PR itself, I can't comment on how debian folks handle things, but IMO this should be listed as optional

```diff
-LXC_USE_NFT="false"
+LXC_USE_NFT="true"
```

**Comment by aleasto** [comment]
Ideally we would just figure out how to coexist with docker when using nftables and enable it by default.

Other distributions are already shipping waydroid with ntables, although the status quo in Fedora for example is to use podman, so it's less of an issue

**Comment by aleasto** [comment]
> Wow, iptables has been deprecated from official Debian releases for 4 years, and Waydroid is still experiencing this issue until now.

FYI, `iptables` on modern systems is an alias for `iptables-nft` which is an iptables-compatible frontend for nft.

**Pull request merged**
