### PR TITLE
Add mainline vulkan support

### PR DESCRIPTION
**Pull request by aleasto**
Attempts to set the correct ro.hardware.vulkan value based on the
loaded drm driver name

### CODE REVIEW

**Comment by Quackdoc** [comment]
do we have images that support this for testing?

**Comment by aleasto** [comment]
> do we have images that support this for testing?

No but they can be compiled from current git

**Comment by aleasto** [comment]
I should add freedreno, broadcom and panfrost too.
And it should probably fallback to lavapipe by default

**Comment by Quackdoc** [comment]
is it worth falling back to lavapipe by default? software vk is probably fine on most modern x86_64 machines, but I worry about arm devices specifically, as there are plenty of low end arm devices floating around with linux, could this wind up causing even more issues then VK just not working on said devices? 

if so maybe default for x86 devices but leave arm to not use lavapipe, at least by default.

**Comment by aleasto** [comment]
What issues are you thinking about? Not much uses vulkan

Since we are declaring that the device [supports vulkan](https://github.com/waydroid/android_device_waydroid_waydroid/blob/lineage-17.1/device.mk#L155-L157) i think it is actually better to make sure we always provide an implementation.

**Comment by Quackdoc** [comment]
on significantly low powered devices, running lavapipe, or other software rendering stuff for that matter can cause severe issues due to the cpu usage, and I know some people are making it run on absurdly ancient hardware. this could present problems in android itself rendering incredibly slowly, or if unlucky, even causing issues for the host OS. for such users falling back to lavapipe could be worse then having no support for vulkan. this could cause issues for people running games with vulkan support. which there are a few on the gplay store. 

though I'm not sure a good way to go about dealing with this one to be honest. would not adding the driver be that bad? iirc vulkanloader should still report that no devices work anyways and fail elegantly. this would be enough to prevent apps from auto detecting vulkan support and using it over opengl assuming it doesnt cause issues. 

Also I might be mistaken since I'm a wee tired seems to be checking for kernel driver for deciding what vulkan driver to load? there are plenty of radeon cards and intel cards that would fall through the gaps with this. not declaring lvp and not supporting vulkan either.

Ideally we could query `VkPhysicalDeviceProperties` using vulkan but that would require using vulkan stuff in the script iirc granted im not familiar with python so that might not actually be too bad? don't know enough to comment. 
another possible solution would be to query vulkaninfo too, but then we add a dependency vulkaninfo...

hm... I don't think this is a good solution, but I don't know of any better ones myself. if this is what waydroid ends up going with, I think an entry in the docs detailing both how to disable lavapipe, or enable it would be necessary to accompany the merge.

**Comment by aleasto** [comment]
> seems to be checking for kernel driver for deciding what vulkan driver to load? there are plenty of radeon cards and intel cards that would fall through the gaps with this

Elaborate?

**Comment by aleasto** [comment]
https://www.phoronix.com/news/Intel-HASVK-Old-Vulkan-Gen7-8 This will be very annoying though.

**Comment by aleasto** [comment]
Will deal with intel when the driver split lands in mesa-stable

**Pull request merged**
