### PR TITLE
gpu: Also mount card node

### PR DESCRIPTION
**Pull request by aleasto**
Necessary for minigbm_gbm_mesa

### CODE REVIEW

**Comment by aleasto** [comment]
I can't remember why i hadn't pushed this

**Comment by JamiKettunen** [comment]
Cool, what does `minigbm_gbm_mesa` bring us? I saw at least one issue about it making some game work: #589

**Comment by Quackdoc** [comment]
does it need it? works fine for me on AMD RX580 without it. is this an intel gpu thing? 

Either way no complaints from me if it's necessary.

**Comment by aleasto** [comment]
https://github.com/waydroid/android_external_minigbm/blob/lineage-18.1/gbm_mesa_driver/gbm_mesa_internals.cpp#L204

An explanation can be found here: https://github.com/robherring/gbm_gralloc/pull/16

**Comment by Quackdoc** [comment]
ahh I see,

**Pull request merged**
